### ISSUE TITLE
Cancancan documentation 

### ISSUE THREAD

**Issue by bricesanchez** [exAspArk/graphql-guard#1]
Hi! 

Thanks for your awesome's work on this gem!

I've followed your [CanCanCan](https://github.com/exAspArk/graphql-guard#cancancan) documentation but it didn't work until i've added this configuration: 

```ruby
# app/graph/graphql_schema.rb
GraphqlSchema = GraphQL::Schema.define do
  query QueryType
  mutation MutationType

  use GraphQL::Guard.new

  resolve_type -> (obj, args, ctx) {
    type_name = obj.class.name
    Schema.types[type_name]
  }
end
```

I use `graphql-guard (~> 1.0.0)` on rails 5.1

Did i missed something?

**Comment by exAspArk** [comment]
Hey!

> it didn't work until i've added this configuration
Where there any errors?

What did you exactly add to fix the problem: `use GraphQL::Guard.new` or `resolve_type`? What's the `graphql-ruby` version do you use?

Thanks

**Comment by bricesanchez** [comment]
> What did you exactly add to fix the problem: 

`use GraphQL::Guard.new`

and i use the latest version of `graphql-ruby` : 1.6.7

**Comment by exAspArk** [comment]
@bricesanchez thanks for your reply!

In the `Usage` section, there are 2 categories:

* [Inline policies](https://github.com/exAspArk/graphql-guard#inline-policies)

The first sentence states "Add `GraphQL::Guard` to your schema":
```ruby
Schema = GraphQL::Schema.define do
  # ...
  use GraphQL::Guard.new
end
```

* [Policy object](https://github.com/exAspArk/graphql-guard#policy-object)

"Pass this object to `GraphQL::Guard`":

```ruby
Schema = GraphQL::Schema.define do
  # ...
  use GraphQL::Guard.new(policy_object: GraphqlPolicy)
end
```

So, in the `Integration` section I was referring to the same `Schema` from the `Usage` section :)

If you find it confusing, feel free to open a Pull Request to update the README. 
I'll be glad to merge it 🙌
