### ISSUE TITLE
Skip authorization on return fields

### ISSUE THREAD

**Issue by egonm12** [exAspArk/graphql-guard#25]
I am having issues with mutations where I return a type that is guarded. Let's say for example I have a mutation where a user can reset the password with a token it got via a mail and I return a UserType.
```
mutation($reset_password_token: String, $password: String) {
    newPassword(
      reset_password_token: $reset_password_token,
      password: $password,
      password_confirmation: $password
  ) { id }
}
```

The problem is that the UserType is guarded but within the mutation I want to skip the UserType guard policy. Is this possible?

**Comment by exAspArk** [comment]
Hey @egonm12, that's a very interesting use case. GraphQL-Guard itself doesn't allow to skip some guards with a mutation. But just as an idea, you could use the `context` to understand whether the execution is after the mutation or not, for example:

```ruby
mutation: ->(obj, args, ctx) do
  user = User.find(...)
  user.change_password(...)
  ctx[:changed_password_user] = user
end

user_guard: ->(obj, args, ctx) do
  ctx[:current_user] == obj || ctx[:changed_password_user] == obj
end
```

Or simply let the user, which perfomed the mutation, be "signed in" after the mutation execution:

```ruby
mutation: ->(obj, args, ctx) do
  user = User.find(...)
  user.change_password(...)
  ctx[current_user] = user
end

user_guard: ->(obj, args, ctx) do
  ctx[:current_user] == obj
end
```
