### ISSUE TITLE
Compatibility with graphql-ruby's new interpreter 

### ISSUE THREAD

**Issue by gopeter** [exAspArk/graphql-guard#28]
At first, thank you very much for the great gem, it saved us a lot of headaches! I just came across that the new (experimental) interpreter of `graphql-ruby` 1.9 does not work with `graphql-guard` (probably because it doesn't call lambdas/procs anymore?). Is there a plan to support the new interpreter in the future?

**Comment by exAspArk** [comment]
Hey @gopeter,

Sorry for the delayed response. I personally don't plan to add support for the new interpreter while it is in the "Experimental" state to avoid any breaking changes in the gem.

![image](https://user-images.githubusercontent.com/577441/61227703-ce99e780-a6f2-11e9-851f-17d2dfd518a8.png)

However, PRs are always welcome :) So people could start testing the compatibility earlier at their own risk.
