### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by dan003400** [exAspArk/graphql-guard#31]
```
class ShopType < Types::BaseObject
  field :title, String, null: false
  field :user, Types::Models::UserType, null: false
end
```

How would you include a guard on this field for the ShopType, we would like to limit the field user to only signed in users, but allow the other fields on a shop to be public without the need for authentication.

**Comment by dan003400** [comment]
```
class ShopType < Types::BaseObject
    field :title, String, null: true

    field :user, Types::Models::UserType, null: true do
      guard ->(obj, args, ctx) { ctx[:current_user] && ctx[:current_shop] }
    end

  end
```

Just for anyone else who is looking to add guarded fields on BaseObjects.

**Comment by exAspArk** [comment]
Thank you @dan003400. Right, the existing documentation was written by using the previous `graphql` gem schema-definition DSL.

For those who would like to contribute and update the readme to use class-based schema definitions, here is an example from the gem specs:

https://github.com/exAspArk/graphql-guard/blob/b0e13cdce93a37a9d853849aa23e63674403f490/spec/fixtures/inline_schema.rb#L40-L64
