### ISSUE TITLE
Use on resolver

### ISSUE THREAD

**Issue by imcvampire** [exAspArk/graphql-guard#38]
Hi,

Can you add `guard` to `Resolver`

Thanks for your open source contributions!

**Comment by exAspArk** [comment]
Hi @imcvampire,

> Can you add `guard` to `Resolver`

I'm sorry, what do you mean? Can you provide more information and examples?

P.S. You can find some code examples in the readme file

**Comment by imcvampire** [comment]
Here is what I do for now

```ruby
field :my_field, resolver: Resolvers::MyFieldResolver do 
  guard -> (_, _, ctx) { ctx[:current_user] }
end
```

```ruby
class MyFieldResolver < GraphQL::Schema::Resolver
  type :id, ID, null: false
end
```

What I want to do

```ruby
field :my_field, resolver: Resolvers::MyFieldResolver
```

```ruby
class MyFieldResolver < GraphQL::Schema::Resolver
  type :id, ID, null: false
  guard -> (_, _, ctx) { ctx[:current_user] }
end
```

**Comment by imcvampire** [comment]
And, I don't see any example about using with `Resolver`

**Comment by imcvampire** [comment]
Hi @exAspArk!

**Comment by quinnvaughn** [comment]
I'm having the same issue.

**Comment by tinynumbers** [comment]
@imcvampire @exAspArk any answer / solution to this? I have the same question.
