### ISSUE TITLE
Add support for arguments

### ISSUE THREAD

**Issue by 23tux** [exAspArk/graphql-guard#44]
I'd like to mask certain arguments so they are hidden in the schema. I'm currently playing around with this

```
# in an initializer
GraphQL::Argument.accepts_definitions(mask: GraphQL::Define.assign_metadata_key(:mask))
GraphQL::Schema::Argument.accepts_definition(:mask)
```

and then use it like this

```
argument :foo, String, required: false, mask: ->(ctx) { false }
```

Is this the right way to do it? And can someone explain why I need to define the mask on `GraphQL::Argument` AND `GraphQL::Schema::Argument`?

**Comment by 23tux** [comment]
I have the code above working in production, so it seems like the right way. But I'd still like to know, if this is the intended way to support arguments.

**Comment by asgeo1** [comment]
Sad that this got auto-closed. I was looking to do this myself, would be good to get the [PR](https://github.com/exAspArk/graphql-guard/pull/43) merged
