### ISSUE TITLE
Missing magic comment `# frozen_string_literal: true` and "Freeze mutable objects assigned to constants.".

### ISSUE THREAD

**Issue by johnunclesam** [exAspArk/graphql-guard#9]
I have this graphql_policy.rb:

```
class GraphqlPolicy
  RULES = {

    Types::QueryType => {
      '*': ->(_obj, _args, ctx) { ctx[:current_user] }
    }
  }

  def self.guard(type, field)
    RULES.dig(type, field)
  end
end
```

Now using `rubocop` on it I got this:

![image](https://user-images.githubusercontent.com/21275217/33352266-69fe02c0-d4a8-11e7-86fb-6d212ba80170.png)

**What we can do?**

**Comment by johnunclesam** [comment]
Maybe `RULES.freeze = {`?

**Comment by exAspArk** [comment]
@johnunclesam the issue doesn't seem to be related to the gem. You or your IDE is using https://github.com/bbatsov/rubocop which checks the syntax of your code.

* Add the `# frozen_string_literal: true` comment on top of your file to make the strings defined in the file immutable

* Add `RULES = { ... }.freeze` to make your hash object immutable
